// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Card$ReactTemplate = require("./Card.bs.js");

var cardList = ReasonReact.statelessComponent("CardList");

function make(allText, color, _children) {
  return /* record */[
          /* debugName */cardList[/* debugName */0],
          /* reactClassInternal */cardList[/* reactClassInternal */1],
          /* handedOffState */cardList[/* handedOffState */2],
          /* willReceiveProps */cardList[/* willReceiveProps */3],
          /* didMount */cardList[/* didMount */4],
          /* didUpdate */cardList[/* didUpdate */5],
          /* willUnmount */cardList[/* willUnmount */6],
          /* willUpdate */cardList[/* willUpdate */7],
          /* shouldUpdate */cardList[/* shouldUpdate */8],
          /* render */(function (_self) {
              var cards = $$Array.map((function (text) {
                      return ReasonReact.element(undefined, undefined, Card$ReactTemplate.make(text, color, /* array */[]));
                    }), allText);
              return React.createElement("div", undefined, cards);
            }),
          /* initialState */cardList[/* initialState */10],
          /* retainedProps */cardList[/* retainedProps */11],
          /* reducer */cardList[/* reducer */12],
          /* jsElementWrapped */cardList[/* jsElementWrapped */13]
        ];
}

exports.cardList = cardList;
exports.make = make;
/* cardList Not a pure module */
