// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Random = require("bs-platform/lib/js/random.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Coordinator$ReactTemplate = require("./Coordinator.bs.js");

var promises = $$Array.map((function (filepath) {
        return fetch(filepath).then((function (prim) {
                          return prim.text();
                        })).then((function (text) {
                        return Promise.resolve(text.split("\n"));
                      })).then((function (texts) {
                      Random.init(Date.now() | 0);
                      var l = texts.length;
                      for(var i = l - 1 | 0; i >= 0; --i){
                        var r = Random.$$int(i + 1 | 0);
                        var tmp = Caml_array.caml_array_get(texts, i);
                        Caml_array.caml_array_set(texts, i, Caml_array.caml_array_get(texts, r));
                        Caml_array.caml_array_set(texts, r, tmp);
                      }
                      return Promise.resolve(texts);
                    }));
      }), /* array */[
      "/assets/black.txt",
      "/assets/white.txt"
    ]);

Promise.all(promises).then((function (cards) {
        var lCards = $$Array.map($$Array.to_list, cards);
        return Promise.resolve(ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Coordinator$ReactTemplate.make(Caml_array.caml_array_get(lCards, 0), Caml_array.caml_array_get(lCards, 1), /* array */[])), "coordinator"));
      }));

exports.promises = promises;
/* promises Not a pure module */
