// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Card$ReactTemplate = require("./Card.bs.js");

var component = ReasonReact.statelessComponent("Player");

function make(update, player, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var cards = $$Array.map((function (c) {
                      return ReasonReact.element(undefined, undefined, Card$ReactTemplate.make(update, c, /* White */0, /* array */[]));
                    }), $$Array.of_list(player[/* availableCards */1]));
              return React.createElement("div", undefined, React.createElement("strong", undefined, player[/* name */3]), React.createElement("br", undefined), React.createElement("div", {
                              style: {
                                display: "flex",
                                flexWrap: "wrap"
                              }
                            }, cards));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
