// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function load(param) {
  return fetch("./black.txt").then((function (prim) {
                  return prim.text();
                })).then((function (text) {
                return Promise.resolve(text);
              }));
}

exports.load = load;
/* No side effect */
