// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

function load(param) {
  return fetch("/assets/black.txt").then((function (prim) {
                  return prim.text();
                })).then((function (text) {
                return Promise.resolve(Caml_array.caml_array_get(text.split("\n"), 0));
              }));
}

exports.load = load;
/* No side effect */
